name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - fri-1.15

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Configure CMake Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - name: Build Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: cmake --build ${{github.workspace}}/build
      - name: Configure CMake Windows
        if: matrix.os == 'windows-latest'
        run: cmake -B ${{github.workspace}}/build
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: cmake --build ${{github.workspace}}/build --config Release
